# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "$"
[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](red)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@[$hostname](bold green):"
trim_at = ".jinkosystems.co.uk"
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold blue"
format = "[$path]($style)[$read_only]($read_only_style)"
read_only = "ï€£"
home_symbol = "~"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[jobs]
symbol = " +"
style = "bold green"
format = "[$symbol$number]($style)"

[cmd_duration]
min_time = 180_000
format = " ğŸ•™[$duration]($style)"

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true
